default:
  system:
    terminal:
      prefix: 2090
  user:
    email: usertest@gmail.com
    firstname: User
    lastname: Test
sendgrid:
  api:
    key: RGtvGATjRuWv1XtNUk2LZw
spring:
  application:
    logstash:
      port: 5000
      ip: 62.171.189.125
  mail:
    default-encoding: UTF-8
    host: mail.tegritech.ng
    password: H0l1n355@1234
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    protocol: smtp
    username: no-reply@tegritech.ng
  datasource:
    password: Ay@w0la
    url: jdbc:postgresql://84.247.188.72:5432/translite
    username: ayoola
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

mail:
  from: ${spring.mail.username}
  name: Tegritech TMS
mailing-list: ayenijeremiah@gmail.com,tosyne.eksu@gmail.com